### ISSUE TITLE
Script question...

### ISSUE THREAD

**Issue by jamo** [testmycode/tmc-cli#332]
https://github.com/tmc-cli/tmc-cli/blob/master/scripts/stub.sh#L110-L113

Why not just `cat tmc.new > tmc`

**Comment by Salmela** [comment]
I thought that if the move fails then the user at least has the original tmc binary. There isn't proper error code checks to make this actually work, but that was the idea.

I will do something to it if I have time.

**Comment by Salmela** [comment]
This was fixed in #348 .
