### ISSUE TITLE
tmc info shows zero completed exercises

### ISSUE THREAD

**Issue by mgunyho** [testmycode/tmc-cli#333]
I completed some exercises in the Aalto C summer course a few days ago, using 0.5.1. Today tmc tried to update, but it failed so I downloaded the latest release from Github. Now running `tmc info` shows no completed exercises, but tmc.mooc.fi shows the completed exercises correctly.

`tmc update` says all exercises are up-to-date, I've tried to logout and login again.

I'm running Ubuntu and Bash.

**Comment by mgunyho** [comment]
Completing an exercise that made more exercises available and running `tmc update` seems to have fixed the issue, `info` now reports the correct numbers.

**Comment by Salmela** [comment]
Incorrect status of completed exercises after submit was fixed in 0.6.3 at commit f527be7 .
I try to improve error messages from auto updates at some point. At some point there was certificate problem with githubs cdn. The auto update problem could be related to it.
